name: nisar_37
channels:
  - conda-forge
  - defaults
dependencies:
#  - python=3.11
  - numpy
  - matplotlib
  - gdal
  - scipy
  - pandas
  - scikit-learn
  - ipywidgets
  - rasterio
  - h5py
  - earthaccess
  - pyproj
  - geopandas
  - asf_search 
  - fpdf
  - tqdm
  - boto3
  - jupyter
  - ipykernel
  - notebook
  - nb_conda_kernels  
  - pre-commit  
  - plotly
  - libgdal-netcdf
  - isce3
  
